# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FtpClient.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class UiFTPClient(object):
    def setupUi(self, FTPClient):
        FTPClient.setObjectName("FTPClient")
        FTPClient.setEnabled(True)
        FTPClient.resize(1224, 688)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FTPClient.sizePolicy().hasHeightForWidth())
        FTPClient.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(FTPClient)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.usernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameInput.setGeometry(QtCore.QRect(10, 110, 113, 20))
        self.usernameInput.setObjectName("usernameInput")
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(10, 90, 61, 21))
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(10, 160, 47, 13))
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(10, 180, 113, 20))
        self.passwordInput.setObjectName("passwordInput")
        self.portLabel = QtWidgets.QLabel(self.centralwidget)
        self.portLabel.setGeometry(QtCore.QRect(10, 240, 47, 13))
        self.portLabel.setObjectName("portLabel")
        self.portInput = QtWidgets.QLineEdit(self.centralwidget)
        self.portInput.setGeometry(QtCore.QRect(10, 260, 51, 20))
        self.portInput.setObjectName("portInput")
        self.hostInput = QtWidgets.QLineEdit(self.centralwidget)
        self.hostInput.setGeometry(QtCore.QRect(10, 50, 113, 20))
        self.hostInput.setText("")
        self.hostInput.setObjectName("hostInput")
        self.hostLabel = QtWidgets.QLabel(self.centralwidget)
        self.hostLabel.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.hostLabel.setObjectName("hostLabel")
        self.connectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.connectBtn.setGeometry(QtCore.QRect(10, 310, 75, 23))
        self.connectBtn.setObjectName("connectBtn")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(139, 29, 1081, 541))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.containerDir = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.containerDir.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.containerDir.setContentsMargins(0, 0, 0, 0)
        self.containerDir.setSpacing(20)
        self.containerDir.setObjectName("containerDir")
        self.localDir = QtWidgets.QVBoxLayout()
        self.localDir.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.localDir.setContentsMargins(-1, -1, 0, -1)
        self.localDir.setSpacing(10)
        self.localDir.setObjectName("localDir")
        self.localLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.localLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.localLabel.setObjectName("localLabel")
        self.localDir.addWidget(self.localLabel)
        self.containerLocalDir = QtWidgets.QHBoxLayout()
        self.containerLocalDir.setObjectName("containerLocalDir")
        self.localTreeDir = QtWidgets.QTreeView(self.horizontalLayoutWidget)
        self.localTreeDir.setDragEnabled(True)
        self.localTreeDir.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.localTreeDir.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.localTreeDir.setObjectName("localTreeDir")
        self.containerLocalDir.addWidget(self.localTreeDir)
        self.localDir.addLayout(self.containerLocalDir)
        self.containerDir.addLayout(self.localDir)
        self.remoteDir = QtWidgets.QVBoxLayout()
        self.remoteDir.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.remoteDir.setSpacing(10)
        self.remoteDir.setObjectName("remoteDir")
        self.remoteLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.remoteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.remoteLabel.setObjectName("remoteLabel")
        self.remoteDir.addWidget(self.remoteLabel)
        self.containerRemoteDir = QtWidgets.QHBoxLayout()
        self.containerRemoteDir.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.containerRemoteDir.setObjectName("containerRemoteDir")
        self.remoteTreeDir = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        self.remoteTreeDir.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.remoteTreeDir.setDragEnabled(True)
        self.remoteTreeDir.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.remoteTreeDir.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.remoteTreeDir.setObjectName("remoteTreeDir")
        self.containerRemoteDir.addWidget(self.remoteTreeDir)
        self.remoteDir.addLayout(self.containerRemoteDir)
        self.containerDir.addLayout(self.remoteDir)
        FTPClient.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FTPClient)
        self.statusbar.setObjectName("statusbar")
        FTPClient.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(FTPClient)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1224, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        FTPClient.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(FTPClient)
        QtCore.QMetaObject.connectSlotsByName(FTPClient)

    def retranslateUi(self, FTPClient):
        _translate = QtCore.QCoreApplication.translate
        FTPClient.setWindowTitle(_translate("FTPClient", "FTPClient"))
        self.usernameLabel.setText(_translate("FTPClient", "Username"))
        self.passwordLabel.setText(_translate("FTPClient", "Password"))
        self.portLabel.setText(_translate("FTPClient", "Port"))
        self.hostLabel.setText(_translate("FTPClient", "Host"))
        self.connectBtn.setText(_translate("FTPClient", "Connect"))
        self.localLabel.setText(_translate("FTPClient", "Local"))
        self.remoteLabel.setText(_translate("FTPClient", "Remote"))
        self.remoteTreeDir.headerItem().setText(0, _translate("FTPClient", "Filename"))
        self.remoteTreeDir.headerItem().setText(1, _translate("FTPClient", "Type"))
        self.remoteTreeDir.headerItem().setText(2, _translate("FTPClient", "Remote Path"))
        self.menuMenu.setTitle(_translate("FTPClient", "Menu"))
        self.menuAbout.setTitle(_translate("FTPClient", "About"))
